### ISSUE TITLE
Website translation doesn't translate content

### ISSUE THREAD

**Issue by prryplatypus** [kiosion/kio.dev#678]
I was having a look at ur website because #Twitter and realised that when you click the "FR" option in the bottom right menu, the blog posts themselves aren't translated (for example https://kio.dev/fr/work/kio.dev). Not sure if intentional or not, but thought I'd make you aware, as it took me some time to realise what was happening and it felt like it wasn't working at first.ç

Since it uses ChatGPT for the rest (I think?) then it might be worth adding to that :)

**Comment by kiosion** [comment]
Yeah, the posts, projects, and about/now page aren't static. I'm working on integrating the Google Translate API to try and translate them. ChatGPT isn't used for anything though, not sure what you mean by that? The i18n lang files are here: [EN](https://github.com/kiosion/kio.dev/blob/main/svelte-app/src/languages/en.json) / [FR](https://github.com/kiosion/kio.dev/blob/main/svelte-app/src/languages/fr.json)

**Comment by prryplatypus** [comment]
Oh I thought it used ChatGPT because while it translated it the loading spinner mentioned something about it haha

**Comment by kiosion** [comment]
Oh yeah that's a joke lol, just one of the loading phrases

**Comment by kiosion** [comment]
Partly done w/ https://github.com/kiosion/kio.dev/commit/a86ff5a2d5fda58355f2214453d2a43ba5de009f :stuck_out_tongue:

**Comment by prryplatypus** [comment]
:wohoo:
